
CREATE DATABASE IF NOT EXISTS TechSolutionDB;
USE TechSolutionDB;

CREATE TABLE CLIENTES (
    Codigo INT PRIMARY KEY,
    CNPJ VARCHAR(18) NOT NULL,
    RazaoSocial VARCHAR(100) NOT NULL,
    RamoDeAtividade VARCHAR(50),
    DataDeCadastramento DATE,
    PessoaDeContato VARCHAR(50)
);

ALTER TABLE CLIENTES ADD COLUMN StatusCliente VARCHAR(20);
DROP TABLE IF EXISTS CLIENTES;

CREATE TABLE EMPREGADOS (
    Matricula INT PRIMARY KEY,
    Nome VARCHAR(100) NOT NULL,
    Cargo VARCHAR(50),
    Salario DECIMAL(10, 2),
    DataDeAdmissao DATE,
    Qualificacoes TEXT,
    Endereco VARCHAR(100)
);

ALTER TABLE EMPREGADOS ADD COLUMN StatusEmpregado VARCHAR(20);
DROP TABLE IF EXISTS EMPREGADOS;

CREATE TABLE EMPRESAS (
    CNPJ VARCHAR(18) PRIMARY KEY,
    RazaoSocial VARCHAR(100) NOT NULL,
    PessoaDeContato VARCHAR(50),
    Endereco VARCHAR(100)
);

ALTER TABLE EMPRESAS ADD COLUMN TipoEmpresa VARCHAR(30);
DROP TABLE IF EXISTS EMPRESAS;

CREATE TABLE FORNECEDORES (
    CNPJ VARCHAR(18) PRIMARY KEY,
    RazaoSocial VARCHAR(100) NOT NULL,
    Endereco VARCHAR(100),
    PessoaDeContato VARCHAR(50)
);

ALTER TABLE FORNECEDORES ADD COLUMN StatusFornecedor VARCHAR(20);
DROP TABLE IF EXISTS FORNECEDORES;

CREATE TABLE TIPO_ENDERECO (
    Codigo INT PRIMARY KEY,
    Nome VARCHAR(50) NOT NULL
);

ALTER TABLE TIPO_ENDERECO ADD COLUMN Descricao TEXT;
DROP TABLE IF EXISTS TIPO_ENDERECO;

CREATE TABLE ENDERECOS (
    Numero INT,
    Logradouro VARCHAR(100),
    Complemento VARCHAR(50),
    CEP VARCHAR(10),
    Bairro VARCHAR(50),
    Cidade VARCHAR(50),
    Estado VARCHAR(2),
    TipoEndereco INT,
    FOREIGN KEY (TipoEndereco) REFERENCES TIPO_ENDERECO(Codigo)
);

ALTER TABLE ENDERECOS ADD COLUMN Pais VARCHAR(50);
DROP TABLE IF EXISTS ENDERECOS;

CREATE TABLE ENCOMENDAS (
    Numero INT PRIMARY KEY,
    DataDeInclusao DATE,
    ValorTotal DECIMAL(10, 2),
    ValorDesconto DECIMAL(10, 2),
    ValorLiquido DECIMAL(10, 2),
    IDFormaDePagamento INT,
    QuantidadeParcelas INT,
    ClienteID INT,
    FOREIGN KEY (ClienteID) REFERENCES CLIENTES(Codigo)
);

ALTER TABLE ENCOMENDAS ADD COLUMN StatusEncomenda VARCHAR(20);
DROP TABLE IF EXISTS ENCOMENDAS;

CREATE TABLE PRODUTOS (
    Codigo INT PRIMARY KEY,
    Nome VARCHAR(100) NOT NULL,
    Cor VARCHAR(20),
    Dimensoes VARCHAR(50),
    Peso DECIMAL(5, 2),
    Preco DECIMAL(10, 2),
    TempoDeFabricacao TIME,
    DesenhoDoProduto TEXT,
    HorasDeMaoDeObra DECIMAL(5, 2)
);

ALTER TABLE PRODUTOS ADD COLUMN CategoriaProduto VARCHAR(30);
DROP TABLE IF EXISTS PRODUTOS;

CREATE TABLE TIPOS_COMPONENTE (
    Codigo INT PRIMARY KEY,
    Nome VARCHAR(50) NOT NULL
);

ALTER TABLE TIPOS_COMPONENTE ADD COLUMN Descricao TEXT;
DROP TABLE IF EXISTS TIPOS_COMPONENTE;

CREATE TABLE COMPONENTES (
    Codigo INT PRIMARY KEY,
    Nome VARCHAR(50) NOT NULL,
    QuantidadeEmEstoque INT,
    PrecoUnitario DECIMAL(10, 2),
    Unidade VARCHAR(10),
    TipoComponente INT,
    FOREIGN KEY (TipoComponente) REFERENCES TIPOS_COMPONENTE(Codigo)
);

ALTER TABLE COMPONENTES ADD COLUMN Fabricante VARCHAR(50);
DROP TABLE IF EXISTS COMPONENTES;

CREATE TABLE MAQUINAS (
    ID INT PRIMARY KEY,
    TempoDeVida INT,
    DataDaCompra DATE,
    DataFimDaGarantia DATE
);

ALTER TABLE MAQUINAS ADD COLUMN StatusMaquina VARCHAR(20);
DROP TABLE IF EXISTS MAQUINAS;

CREATE TABLE RE (
    ID INT PRIMARY KEY,
    QuantidadeNecessaria INT,
    Unidade VARCHAR(10),
    TempoDeUso TIME,
    HorasDeMaoDeObra DECIMAL(5, 2),
    ProdutoID INT,
    FOREIGN KEY (ProdutoID) REFERENCES PRODUTOS(Codigo)
);

ALTER TABLE RE ADD COLUMN TipoRecurso VARCHAR(30);
DROP TABLE IF EXISTS RE;

CREATE TABLE RM (
    ID INT PRIMARY KEY,
    Data DATE,
    Descricao TEXT,
    MaquinaID INT,
    FOREIGN KEY (MaquinaID) REFERENCES MAQUINAS(ID)
);

ALTER TABLE RM ADD COLUMN Responsavel VARCHAR(50);
DROP TABLE IF EXISTS RM;

CREATE TABLE RS (
    ID INT PRIMARY KEY,
    Quantidade INT,
    DataDeNecessidade DATE,
    ComponenteID INT,
    FOREIGN KEY (ComponenteID) REFERENCES COMPONENTES(Codigo)
);

ALTER TABLE RS ADD COLUMN FornecedorID VARCHAR(18);
DROP TABLE IF EXISTS RS;
