
CREATE DATABASE IF NOT EXISTS InovaTechDB;
USE InovaTechDB;

CREATE TABLE CLIENTES (
    ClienteID INT PRIMARY KEY AUTO_INCREMENT,
    Nome VARCHAR(100) NOT NULL,
    CPF VARCHAR(11) UNIQUE NOT NULL,
    DataNascimento DATE,
    Endereco VARCHAR(200),
    StatusFidelidade VARCHAR(20)  
);
ALTER TABLE CLIENTES ADD COLUMN Email VARCHAR(100);
DROP TABLE IF EXISTS CLIENTES;

CREATE TABLE PRODUTOS (
    ProdutoID INT PRIMARY KEY AUTO_INCREMENT,
    Nome VARCHAR(100) NOT NULL,
    Categoria VARCHAR(50),
    Preco DECIMAL(10, 2) NOT NULL,
    QuantidadeEstoque INT NOT NULL,
    FornecedorID INT,  
    FOREIGN KEY (FornecedorID) REFERENCES FORNECEDORES(FornecedorID)
);
ALTER TABLE PRODUTOS ADD COLUMN Descricao TEXT;
DROP TABLE IF EXISTS PRODUTOS;

CREATE TABLE FORNECEDORES (
    FornecedorID INT PRIMARY KEY AUTO_INCREMENT,
    Nome VARCHAR(100) NOT NULL,
    Contato VARCHAR(100),
    Telefone VARCHAR(15),
    Endereco VARCHAR(200)
);
ALTER TABLE FORNECEDORES ADD COLUMN Email VARCHAR(100);
DROP TABLE IF EXISTS FORNECEDORES;

CREATE TABLE VENDAS (
    VendaID INT PRIMARY KEY AUTO_INCREMENT,
    ClienteID INT, 
    DataVenda DATE NOT NULL,
    FormaPagamento VARCHAR(20),
    FOREIGN KEY (ClienteID) REFERENCES CLIENTES(ClienteID)
);
ALTER TABLE VENDAS ADD COLUMN Desconto DECIMAL(10, 2);
DROP TABLE IF EXISTS VENDAS;

CREATE TABLE VENDAS_PRODUTOS (
    VendaID INT,
    ProdutoID INT,
    Quantidade INT NOT NULL,
    PRIMARY KEY (VendaID, ProdutoID),
    FOREIGN KEY (VendaID) REFERENCES VENDAS(VendaID),
    FOREIGN KEY (ProdutoID) REFERENCES PRODUTOS(ProdutoID)
);
ALTER TABLE VENDAS_PRODUTOS ADD COLUMN PrecoUnitario DECIMAL(10, 2);
DROP TABLE IF EXISTS VENDAS_PRODUTOS;

CREATE TABLE PAGAMENTOS (
    PagamentoID INT PRIMARY KEY AUTO_INCREMENT,
    ClienteID INT, 
    DataPagamento DATE NOT NULL,
    Valor DECIMAL(10, 2) NOT NULL,
    Status VARCHAR(10) CHECK (Status IN ('Pago', 'Pendente')),
    FOREIGN KEY (ClienteID) REFERENCES CLIENTES(ClienteID)
);
ALTER TABLE PAGAMENTOS ADD COLUMN MetodoPagamento VARCHAR(20);
DROP TABLE IF EXISTS PAGAMENTOS;
