
CREATE DATABASE IF NOT EXISTS CompanhiaAereaDB;
USE CompanhiaAereaDB;

CREATE TABLE PASSAGEIROS (
    PASS_CPF VARCHAR(11) PRIMARY KEY,
    PASS_NOME VARCHAR(50) NOT NULL,
    PASS_TELEFONE VARCHAR(15),
    PASS_ENDERECO VARCHAR(100),
    PASS_EMAIL VARCHAR(50)
);

ALTER TABLE PASSAGEIROS ADD COLUMN PASS_NACIONALIDADE VARCHAR(30);

DROP TABLE IF EXISTS PASSAGEIROS;

CREATE TABLE AEROPORTOS (
    AEROP_CODIGO INT PRIMARY KEY,
    AEROP_NOME VARCHAR(50) NOT NULL,
    AEROP_LONGITUDE DECIMAL(10,6),
    AEROP_LATITUDE DECIMAL(10,6),
    AEROP_PAIS VARCHAR(30),
    AEROP_CIDADE VARCHAR(50)
);

ALTER TABLE AEROPORTOS ADD COLUMN AEROP_CAPACIDADE INT;

DROP TABLE IF EXISTS AEROPORTOS;

CREATE TABLE AERONAVES (
    AERON_PREFIXO VARCHAR(10) PRIMARY KEY,
    AERON_FABRICANTE VARCHAR(50),
    AERON_CAPACIDADE INT,
    AERON_AUTONOMIA DECIMAL(5,2),
    AERON_ANOFABR INT,
    AERON_MODELO VARCHAR(50)
);

ALTER TABLE AERONAVES ADD COLUMN AERON_PESO_MAX DECIMAL(10,2);

DROP TABLE IF EXISTS AERONAVES;

CREATE TABLE FUNCIONARIOS (
    FUNC_ID INT PRIMARY KEY,
    FUNC_NOME VARCHAR(50) NOT NULL,
    FUNC_DATANASC DATE,
    FUNC_ENDERECO VARCHAR(100),
    FUNC_CPF VARCHAR(11),
    FUNC_FUNCAO VARCHAR(30)
);

ALTER TABLE FUNCIONARIOS ADD COLUMN FUNC_SALARIO DECIMAL(10,2);

DROP TABLE IF EXISTS FUNCIONARIOS;

CREATE TABLE VOOS (
    VOO_ID INT PRIMARY KEY,
    VOO_DATA DATE,
    VOO_HORA TIME,
    VOO_AEROP_ORIGEM INT,
    VOO_AEROP_DESTINO INT,
    VOO_AERONAVE VARCHAR(10),
    FOREIGN KEY (VOO_AEROP_ORIGEM) REFERENCES AEROPORTOS(AEROP_CODIGO),
    FOREIGN KEY (VOO_AEROP_DESTINO) REFERENCES AEROPORTOS(AEROP_CODIGO),
    FOREIGN KEY (VOO_AERONAVE) REFERENCES AERONAVES(AERON_PREFIXO)
);

ALTER TABLE VOOS ADD COLUMN VOO_DURACAO TIME;

DROP TABLE IF EXISTS VOOS;

CREATE TABLE RESERVAS (
    RESERVA_COD INT PRIMARY KEY,
    VOO_ID INT,
    PASS_CPF VARCHAR(11),
    FOREIGN KEY (VOO_ID) REFERENCES VOOS(VOO_ID),
    FOREIGN KEY (PASS_CPF) REFERENCES PASSAGEIROS(PASS_CPF)
);

ALTER TABLE RESERVAS ADD COLUMN RESERVA_DATA DATE;

DROP TABLE IF EXISTS RESERVAS;

CREATE TABLE OPERACAO_VOO (
    VOO_ID INT,
    FUNC_ID INT,
    PRIMARY KEY (VOO_ID, FUNC_ID),
    FOREIGN KEY (VOO_ID) REFERENCES VOOS(VOO_ID),
    FOREIGN KEY (FUNC_ID) REFERENCES FUNCIONARIOS(FUNC_ID)
);

ALTER TABLE OPERACAO_VOO ADD COLUMN OPERACAO_HORA_INICIO TIME;

DROP TABLE IF EXISTS OPERACAO_VOO;
